# Generated by Django 3.2.3 on 2021-05-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_agency', models.CharField(max_length=255, verbose_name='ANGÊNCIAS')),
                ('comments', models.TextField(blank=True, verbose_name='OBS')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, verbose_name='TIPOS DE PRODUTO')),
                ('comments', models.TextField(blank=True, verbose_name='OBS')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_secure', models.CharField(max_length=255, verbose_name='TIPOS DE SEGUROS')),
                ('comments', models.TextField(blank=True, verbose_name='OBS')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NOME DO CLIENTE')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='NÚMERO DA CONTA')),
                ('gerency', models.CharField(blank=True, max_length=255, verbose_name='NOME DO GERENTE')),
                ('policy', models.CharField(max_length=30, verbose_name='NÚMERO DA APOLICE')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='VALOR PAGO')),
                ('tel1', models.CharField(blank=True, max_length=10, verbose_name='TELEFONE OPÇÃO 1')),
                ('tel2', models.CharField(blank=True, max_length=10, verbose_name='TELEFONE OPÇÃO 2')),
                ('cel1', models.CharField(blank=True, max_length=11, verbose_name='CELULAR OPÇÃO 1')),
                ('cel2', models.CharField(blank=True, max_length=11, verbose_name='CELULAR OPÇÃO 2')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='E-MAIL')),
                ('comments', models.TextField(blank=True, verbose_name='OBS')),
                ('date_contract', models.DateField(blank=True, null=True, verbose_name='DATA SEGURO')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.agency', verbose_name='AGÊNCIA')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.product', verbose_name='PRODUTO')),
                ('secure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.secure', verbose_name='SEGURO')),
            ],
        ),
    ]
